### ISSUE TITLE
What's the buildId of config?

### ISSUE THREAD

**Issue by whywilson** [manojkumarlinux/Simple-Apns#2]
Thank you for your sharing. But could you please make an explanation of the config?
Is the buidId a custom field?
Is the key.pem from the APNS p12 to pem certificate?
And is it possible to change the 64-bit token to tokenString?
Thank you in advance.

**Comment by manojkumar-net** [comment]
1. Build ID means - `com.example.app`
2. For .pem file your right. Use this command to create your .pem file. -  `openssl pkcs12 -in app_pushnotification.p12 -out app_pushnotification.pem -nodes –clcerts` 
3. 64 - bit token means token string (device token). both (you and me) are the same.  
     Example: `8ae32328a36368xd8fc1fdfc1b820exa2d7f36167fa9b6ex37a4bdx09xd6xab4. (count of the char is 64)`
Thanks.

**Comment by whywilson** [comment]
Thank you for the update. And I've fixed that all above.
I've tried certificate to pem and cert key to pem. But both "response":0.

And there are 2 errors in the Response.php file. In line 10 the comma is missing and the line 50 the response code is in some errors.

**Comment by manojkumar-net** [comment]
Thank you for your valuable time to address this. 
Now I changed could you please check this.
